FROM oven/bun:1

WORKDIR /usr/src/app

COPY packages ./packages
COPY bun.lock ./bun.lock

COPY package.json ./package.json
COPY turbo.json ./turbo.json

COPY apps/backend ./apps/backend
ENV DATABASE_URL=postgresql://postgres:mysecret@localhost:5433/postgres

RUN bun install
RUN bun run --filter=@repo/db build
RUN bun run db:generate

EXPOSE 8080

CMD ["bun", "run", "start:backend"]