name: Deploy to backend
on:
  push:
    branches: [ main ] #trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2 # clone the codebase to ubuntu machine{github actions]
      
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: ketansayal2004/todo-app-backend:${{ github.sha }} # github commit id
      - name: Deploy to the VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@3.90.144.148 << 'EOF'
          
          # Pull latest image
          docker pull ketansayal2004/todo-app-backend:${{ github.sha }}

          # Stop old container (ignore error)
          docker stop user_backend || true
          docker rm user_backend || true

          # Run new container with ENV
          docker run -d \
            --name user_backend \
            -p 8080:8080 \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            ketansayal2004/todo-app-backend:${{ github.sha }}

          EOF
      

      